### ISSUE TITLE
jsHint or JSCS is linting library (fusioncharts)

### ISSUE THREAD

**Issue by lawrence1949** [taylor1791/Arbiter-SubPub#2]
In my gulp file line 76:
browser: [ 'app/**/*.js', '!app/lib/**/_.js', '!app/__/_.test.js' ]  
This will exclude fusionchart from linting. But I lost it when I run the build task --- cyclops-crush.

If I remove the the library from this line:
browser: [ 'app/**/*.js',  '!app/**/*.test.js' ]
It will be included when I ran cyclops-crush, but jsHint or JSCS is also linting the library, which makes the application extremely slow.

**Comment by taylor1791** [comment]
Please open this on [taylor1791/front-end-work-flow](https://github.com/taylor1791/front-end-work-flow/)
