### ISSUE TITLE
ignoring persisted messages

### ISSUE THREAD

**Issue by taylor1791** [taylor1791/Arbiter-SubPub#5]
Currently one test is disabled because it fails and I believe the code should work based on [arbiterjs.com](http://arbiterjs.com) in the "Ignore persisted messages" section. Currently `spy` is executed unless I make `{ persist: true }` on the line 5.  If this is the expected behavior, then the docs should be updated. Can @matt-kruse verify one way or the other?

```
1 it( 'allows late subscribers to ignore persisted message', function() {
2   var spy = jasmine.createSpy();
3
4   this.arbiter.publish( 'msg', null, { persist: true } );
5   this.arbiter.subscribe( 'msg', { persist: false }, spy );
6
7   expect( spy ).not.toHaveBeenCalled();
8} );
```

**Comment by matt-kruse** [comment]
Oops, I missed this. Yes, the logic appears to be reversed. persist:false should ignore persisted messages. Bug.

**Comment by taylor1791** [comment]
Arbiter now ignores persisted messages when subscribing if `persist` is strictly equal to false. Loose equality was not an option as `undefined == false`. Alternatively, we could distinguish `{persist: undefined} from {}`. However, I would vote against that since it would be confusing at first.
